#!/usr/bin/env python3

import sys
import webbrowser
from pdfminer.high_level import extract_text 
import tempfile

if len(sys.argv) < 2:
    print("Usage:pdf2site <pdf_file>")
    sys.exit(1)

pdf_file = sys.argv[1]

text = extract_text(pdf_file)

html = f"<html><body><pre>{text}</pre></body></html>"

tmp = tempfile.NamedTemporaryFile(delete=False, suffix='.html')
tmp.write(html.encode('utf-8'))
tmp.close()

print(f"Opening {tmp.name}")

webbrowser.get('chrome').open("file://"+tmp.name)
